Skeleton for SWESARR
snowex-hackweek/website2022 pull request #47
Opened 2022-06-24 06:02 UTC by db1950

Hi everyone.  This is a skeleton for SWESARR's tutorial page.

* I need to get access to both the main github repository for editing and the cloud computing resources to test this build for the website. I've tested this on my local computer, and I think it should work fine considering how simple it is.

* I placed this tutorial under "day 3" following the format of 2021's hackweek. It doesn't seem like there's a set table-of-contents structure right now, so please reject this if this goes against the intended table-of-contents structure for 2022.

thanks!

2022-06-24 06:09 UTC, db1950 commented
I apologize. I was looking at a local installation of last year's table of contents. It looks like it was updated!
https://snowex-hackweek.github.io/website/intro.html

Either way, I would like to group the SWESARR tutorial with other groups. I considered putting it under "NASA Missions", "Microwave Missions", "SWE Missions", "Airborne Missions", etc. but I don't think that's a decision I should make. That's why I struck with "Day 3."

2022-06-24 16:14 UTC, scottyhq commented
thanks for opening this @db1950 

> I need to get access to both the main github repository for editing and the cloud computing resources to test this build  

Sorry! not sure why you weren't already added there, should be good to go now. 

> Either way, I would like to group the SWESARR tutorial with other groups I considered putting it under "NASA Missions", "Microwave Missions", "SWE Missions", "Airborne Missions".  

@jomey any preference? Whatever you think is best. Can always reorganize later!

2022-06-24 16:15 UTC, scottyhq commented on book/_toc.yml
> +                - file: tutorials/microwave/swesarr
```suggestion
            - file: tutorials/microwave/index
              sections:
                - file: tutorials/microwave/swesarr/index
                - file: tutorials/microwave/swesarr/swesarr_tut
```

2022-06-24 16:35 UTC, jomey commented
> @jomey any preference? Whatever you think is best. Can always reorganize later!

My vote would be a specific group like "Microwave Missions" and agree that it can be changed later (and probably will as we shake things out).

2022-06-27 16:33 UTC, scottyhq requested changes
@db1950 you can either commit the above 'suggested' changes, or modify the folder structure in the table of contents another way

2022-07-03 21:17 UTC, db1950 commented
I'm not sure why the add-preview is failing here, and the error generated isn't making sense to me?

2022-07-03 21:41 UTC, jomey commented on book/tutorials/day_3.md
> +```
Looks like this file snuck in when porting the notebook from last year. Should be safe to remove

2022-07-03 21:50 UTC, jomey commented on book/_toc.yml
> +                  title: SWESARR
I think the TOC entry should look like this to make the preview happy:
```
        - file: tutorials/microwave/index
          title: Microwave Tutorials
          sections:
            - file: tutorials/microwave/swesarr/index
            sections:
              - file: tutorials/microwave/swesarr/swesarr_tut
                title: SWESARR
```

2022-07-04 23:45 UTC, db1950 commented
Is this file structure not possible on the website? I can't see why this is failing.

2022-07-05 15:47 UTC, jomey commented
Dylan, note my PR #74 to suggest your desired structure as I understood it.

2022-07-06 12:34 UTC, db1950 commented
@jomey resolved all isues in pull request #74, so we can wrap this one up. Thanks, @jomey!!!

2022-07-06 12:34 UTC, closed without merging