Romina's tutorial
snowex-hackweek/website2022 pull request #49
Opened 2022-06-24 17:26 UTC by RomiP

new files for participants for OOP tutorial.
added tutorial to _toc.yml

2022-06-24 19:38 UTC, scottyhq commented on book/_toc.yml
> +        - file: tutorials/OOP
jupyterbook expects a file here, so I recommend a simple `tutorials/OOP/index.md` that just has a title: 
```
# Object Oriented Programming
```

2022-06-24 19:39 UTC, scottyhq requested changes
thanks @RomiP please 'restart kernel and clear outputs' for these notebooks if you want them automatically executed and rendered, otherwise you'll have to add them here: 

https://github.com/snowex-hackweek/website2022/blob/29fc416ec7a24d5d602b0773ed0706b02cf76afe/book/_config.yml#L39-L40

2022-07-05 20:55 UTC, JessicaS11 commented on book/team.yaml
> +      In addition to her research, Romina is actively involved in a software development
```suggestion
      In addition to her research, Romina is actively involved in software development
```

2022-07-05 22:04 UTC, scottyhq approved these changes
thanks @RomiP !

2022-07-05 22:04 UTC, merged