committing a tutorial outline
snowex-hackweek/website2022 pull request #62
Opened 2022-06-28 15:16 UTC by meganmason

2022-06-28 15:49 UTC, meganmason commented
Wondering if the QualityControl test failed because I either didn't clear my outputs or didn't run the notebooks from top to bottom before committing.

2022-06-28 16:02 UTC, scottyhq requested changes
> Wondering if the QualityControl test failed because I either didn't clear my outputs 

Yep, you'll have to 'restart kernal and clear all outputs', save and commit the empty notebook

2022-06-28 16:05 UTC, meganmason commented
Awesome, will do. Also, I'm okay to leave this PR open for a bit as I continue to make changes today. Thanks @scottyhq

2022-06-29 17:14 UTC, meganmason commented
hey @scottyhq and @jomey, I created a new branch and PR for my toc.yml updates. My goal was to be more up-to-date with the Main, and push a small change.

2022-06-29 17:17 UTC, scottyhq commented
You'll actually want to add those changes to the _toc.yml here in your `core-data` branch. that way jupyterbook knows where to put the notebooks you're adding here in relation to other pages on the website.

2022-06-29 17:27 UTC, meganmason commented
Okay, will do! Wishful thinking on my end :) 

I'm guessing the other PR I issued will just be rejected and I can delete that branch?

2022-06-29 17:39 UTC, scottyhq commented on book/_toc.yml
> +           - file: tutorials/data-overview/03_snowexsql_db_querying
```suggestion
        - file: tutorials/core-datasets/index
          title: SnowEx Mission and Dataset Descriptions
          sections:
            - file: tutorials/core-datasets/01_campaigns-overview
            - file: tutorials/core-datasets/02_ground-based-specifics
            - file: tutorials/core-datasets/03_snowexsql_db_querying 
```

2022-06-29 17:43 UTC, scottyhq commented on book/_toc.yml
> +           - file: tutorials/data-overview/03_snowexsql_db_querying
☝️ you can just hit the 'commit suggestion' to fix indent level and path names and it should then try to build

2022-06-29 17:52 UTC, meganmason commented on book/_toc.yml
> +           - file: tutorials/data-overview/03_snowexsql_db_querying
I missed your note about hit 'commit suggestion'. But did go back in and make the changes on the branch, commited, and pushed.

2022-06-29 17:53 UTC, meganmason commented on book/_toc.yml
> +           - file: tutorials/data-overview/03_snowexsql_db_querying
I keep confusing the word 'comit' and 'coment' lately.... so I don't think registered to select the 'commit suggestion' box. 😂

2022-06-29 17:57 UTC, scottyhq commented on book/_toc.yml
> +           - file: tutorials/data-overview/03_snowexsql_db_querying
all good. the spacing is still off by one though, so you need to indent still. Also you'll need to add a file `tutorials/core-datasets/index.md` which can just have the title as content: 
```
# SnowEx Mission and Dataset Descriptions

```

2022-06-29 18:10 UTC, meganmason commented
hmm, not doing too well on the checks (0/4). 😬 When I click the red 'Changes requested' link I don't see anything new that needs attention.  If possible, I'm interested in getting this merged before continuing to develop content.

2022-06-29 18:16 UTC, meganmason reviewed
Little confused by this part. The green (upper right) button says 'Review changes', but everything is green and I don't see something that looks like a 'requested change'?

2022-06-29 18:24 UTC, jomey commented
Looks like your branch was not up to date with `main` when you created your branch.
Want to do a `git merge main` when you are on this branch and push anew?
Some failures look unrelated to your changes and due to having 'old' main content.

2022-06-29 18:44 UTC, meganmason commented
Thanks, @jomey. I'm up to date with the main now, but still, scoring a 0 on the checks? Notebook outputs were all cleared before doing a `git push`
<img width="1332" alt="Screen Shot 2022-06-29 at 12 39 34 PM" src="https://user-images.githubusercontent.com/35740962/176512022-553c5e68-c0f8-4368-8e60-13a2ae32c79a.png">

2022-06-29 18:48 UTC, scottyhq commented
@meganmason you might have missed my comment earlier, copying here

all good. the spacing is still off by one though, so you need to indent still. Also you'll need to add a file `tutorials/core-datasets/index.md` which can just have the title as content:

```
# SnowEx Mission and Dataset Descriptions

```

2022-06-29 18:49 UTC, scottyhq commented on book/_toc.yml
> +           - file: tutorials/core-datasets/03_snowexsql_db_querying
```suggestion
        - file: tutorials/core-datasets/index
          title: SnowEx Mission and Dataset Descriptions
          sections:
            - file: tutorials/core-datasets/01_campaigns-overview
            - file: tutorials/core-datasets/02_ground-based-specifics
            - file: tutorials/core-datasets/03_snowexsql_db_querying 
```

2022-06-29 19:03 UTC, meganmason commented
after @jomey's comment, I probably should have done a `git pull` in my `core-data` branch? I think that's what git wants now since it won't let me `git push` my new index.md file. 
<img width="688" alt="Screen Shot 2022-06-29 at 1 00 47 PM" src="https://user-images.githubusercontent.com/35740962/176515784-deb1b70b-94df-4463-8c94-28bb63b74fbe.png">

2022-06-29 19:05 UTC, scottyhq commented
Right, that message comes up b/c we just committed that last change (Update book/_tock.yml) on GitHub, but you didn't have that change locally. So `git pull` then `git push`

2022-06-29 19:08 UTC, meganmason commented
cool, will do. Just always have to convince myself that a `git pull` on a branch won't overwrite all the branch changes. Since branch changes have been committed I should be assured they won't go away where yah?

2022-06-29 19:18 UTC, scottyhq commented
Awesome! Almost there. Under the 'Details' for the checks you'll see the following:
`/home/runner/work/website2022/website2022/book/tutorials/core-datasets/01_campaigns-overview.ipynb:60002: WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]` 

Jupyter Book is picky about headings for the table of contents. You can't have: 
```
# Title
### Subtitle
```

It needs to be: 
```
# Title
## Subtitle
```

2022-06-29 19:19 UTC, meganmason commented
awh, I recall that from last year! Thought I was being careful.

2022-06-29 19:28 UTC, scottyhq commented
Woohoo! You can now see how things look here https://deploy-preview-62--snowex2022.netlify.app/tutorials/core-datasets/index.html . The remaining failing check is for empty cells in the notebook `notebook cell 7: empty cell` I actually think we're being too strict there, so I'll make a note to change that. But if you remove those placeholder cells for now we can merge

2022-06-29 19:31 UTC, meganmason commented
yay, some green! seems to think I still don't have clean notebooks... I'll be MIA for a bit, but afterward will jump back on!

2022-06-29 19:33 UTC, meganmason commented
copy! I wondered if blank cells would be an issue. I'll address that, but not yet. Thanks, @scottyhq !

2022-07-01 14:15 UTC, meganmason commented
Hey @scottyhq, I see I have some conflicts in the _toc.yml, but I'm not sure how to interpret what git is suggesting.
![Screen Shot 2022-07-01 at 8 13 00 AM](https://user-images.githubusercontent.com/35740962/176911502-ba2d74b7-7f01-4fe4-aafa-a907ae90d10b.png)

2022-07-01 14:27 UTC, meganmason commented
hey @jomey , I've been watching to make sure I keep up with main. I did a `git merge main, git pull, git push` again and am not convinced I'm up to date based on the cool branch tool you showed me. I read this as I'm still 7 commits behind. Maybe it never goes to zero while a PR is open, but the goal is to get a little more up-to-date with the main, verses before when I had a "really old main". 

![Screen Shot 2022-07-01 at 8 22 37 AM](https://user-images.githubusercontent.com/35740962/176913332-be572c6e-e397-4027-b4da-5fb02664d2fa.png)

2022-07-01 15:13 UTC, meganmason commented
we're in the green zone @scottyhq !! (Still adding content to notebooks, but it's the first time all checks have passed). I see 'changes requested' still, but don't see detail on them.

2022-07-01 16:17 UTC, scottyhq commented
> 'changes requested' still, but don't see detail on them. 

That remains until I manually change to 'approved'.  

This looks great, thanks @meganmason ! Nice work loading the dataframe from a gist URL! It looks like the GIF isn't rendering in the preview. I know that the following syntax works (from an icesat-2 hackweektutorial): 

`<img src='https://media0.giphy.com/media/r3Yeh3aAjsyYGObizC/giphy.gif' alt='cloud bouncing and smiling' style='width:350px' />`

https://github.com/ICESAT-2HackWeek/website2022/blob/10229090a94edb3e5734dbc00149b0502ad5396a/book/tutorials/cloud-computing/cloud-computing-tutorial.ipynb?short_path=41df864#L12


But feel free to merge this one whenever, you can always start fresh with additional changes

2022-07-01 16:17 UTC, scottyhq approved these changes

2022-07-01 16:45 UTC, meganmason commented
Fantastic - yes not complete yet, but progress is happening! I'll go ahead and merge and then start fresh when I pick this back up. Thanks for the beta on the gif.

2022-07-01 16:46 UTC, merged