refining content for core-data
snowex-hackweek/website2022 pull request #73
Opened 2022-07-05 05:08 UTC by meganmason

added content to 03_database_preview; 2nd and 3rd examples are nearly complete. Need to finish the geojson part, and recap. Images would help too!

I will add content to notebook 02, and the final map figure in notebook 01

2022-07-06 15:37 UTC, JessicaS11 commented
@meganmason QC picked up a few spelling errors and tagged them. Other than fixing those, are you planning to add more to these tutorials in this PR (i.e. is it ready for review)?

2022-07-06 19:51 UTC, meganmason commented
hi @JessicaS11, yes - still adding content, so it's not ready for a final review. I know I'm past the preferred deadline. (Unfortunately, I'm now limited to short breaks while I attend a 2-day conference).  Thanks for checking in!

2022-07-09 16:42 UTC, micahjohnson150 commented
@meganmason yesterday @scottyhq was having issues with a reference to `ImageData.surveyors` in your notebook. So to move forward he temporarily disabled one of your notebooks. Looks like you fixed the reference to surveyors here but I think it wont render without removing it from the [_config.yml ](https://github.com/snowex-hackweek/website2022/blob/45ad291cbb074503d048bf7f5422de177415ce70/book/_config.yml#L43)

2022-07-10 04:05 UTC, meganmason commented
okay, team! This is ready. There might be some requested changes, a typo, or a check that doesn't pass, but I'm finished with the content. I'll watch the checks and see which ones I can manage.

2022-07-10 05:47 UTC, meganmason commented
thanks @micahjohnson150 for the tip on the _config.yml file. I removed it and pushed anew.

2022-07-10 05:48 UTC, meganmason commented
How does one handle a supposed spell check error that is not an error? In my case it's a table with a site name "BA flux tower" and the request is to change 'BA' to 'BY' or 'BE', which is not correct.

2022-07-10 15:13 UTC, jomey commented
> How does one handle a supposed spell check error that is not an error? In my case it's a table with a site name "BA flux tower" and the request is to change 'BA' to 'BY' or 'BE', which is not correct.

Add the “BA” at the end of this list:
https://github.com/snowex-hackweek/website2022/blob/e4c2652549353647689fbc22aedc77706e95ee88/.github/workflows/qaqc.yaml#L36

2022-07-10 22:39 UTC, meganmason commented
thanks @jomey ! I changed the file on my branch and pushed it up. Could you remind me how to "deploy" the preview?

2022-07-11 02:37 UTC, scottyhq commented on book/tutorials/core-datasets/01_data_coverage.ipynb
> +    "<img src='content/01_campaign_venn_diagram.jpg'>\n",
```suggestion
    "<img src='./content/01_campaign_venn_diagram.jpg'>\n",
```
i think you need relative paths

2022-07-11 02:37 UTC, scottyhq requested changes
@meganmason the preview is automatically updated with each commit, so your content is here https://deploy-preview-73--snowex2022.netlify.app/tutorials/core-datasets/index.html . The images are not rendering currently, I think the paths need to be relative to the notebook (see comment)

2022-07-11 05:27 UTC, meganmason commented
made all images have relative file paths, but the preview still doesn't seem to be rendering them?

2022-07-11 05:30 UTC, meganmason commented
The pattern appears to be all images I have a figure capture for are NOT rendering, the few images without figure captions are okay.

2022-07-11 07:14 UTC, meganmason commented
Images all render and required checks pass. I think we're good to merge by the AM

2022-07-11 11:43 UTC, scottyhq approved these changes

2022-07-11 11:46 UTC, merged